<?php
/**
 * @category design
 * @package rockar_default
 * @author Dmitrijs Sitovs <dmitrijssh@scandiweb.com / dsitovs@gmail.com>
 * @copyright Copyright (c) 2016 Scandiweb, Ltd (http://scandiweb.com)
 * @license http://opensource.org/licenses/afl-3.0.php Academic Free License (AFL 3.0)
 *
 * @var $this Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<html class="loading">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body class="full_width <?php echo $this->getBodyClass() ? $this->getBodyClass() : '' ?>" @mousedown="closeDropDowns">
    <?php echo $this->getChildHtml('after_body_start') ?>
    <?php echo $this->getChildHtml('header') ?>

    <div class="wrapper">
        <div class="outer-container breadcrumbs-wrapper">
            <?php echo $this->getChildHtml('global_notices') ?>
            <?php echo $this->getChildHtml('breadcrumbs') ?>
        </div>

        <div class="grid main-container layout-1-col">
            <div class="messages-wrapper">
                <?php echo $this->getChildHtml('global_messages') ?>
                <?php echo $this->getChildHtml('messages') ?>
            </div>
            <div class="main">
                <?php echo $this->getChildHtml('content') ?>
            </div>
        </div>
    </div>

    <?php echo $this->getChildHtml('footer') ?>
    <?php echo $this->getChildHtml('before_body_end') ?>
    <?php echo $this->getAbsoluteFooter() ?>
    <?php echo $this->getChildHtml('before_body_end_scripts') ?>
</body>
</html>
