<?php
/**
 * @category  Peppermint
 * @package   Peppermint
 * @author    Krists Dadzitis <techteam@rockar.com>
 * @copyright Copyright (c) 2020 Rockar Ltd (http://rockar.com)
 */

/**
 * @var $this Peppermint_Sales_Block_Adminhtml_Sales_Items_Column_Name
 */
?>

<?php if ($_item = $this->getItem()): ?>
    <h5 class="title">
        <span id="order_item_<?php echo $_item->getId(); ?>_title"><?php echo $this->escapeHtml($this->getItemName($_item)); ?></span>
    </h5>

    <div>
        <strong><?php echo $this->helper('sales')->__('SKU'); ?>:</strong> <?php echo implode('<br />', Mage::helper('catalog')->splitSku($this->escapeHtml($this->getSku()))); ?>
    </div>

    <?php foreach ($this->getAdditionalAttributes($_item) as $attribute): ?>
        <div><strong><?php echo $attribute['label']; ?>:</strong> <?php echo $attribute['value']; ?></div>
    <?php endforeach; ?>

    <?php if ($this->getOrderOptions()): ?>
        <dl class="item-options">
        <?php foreach ($this->getOrderOptions() as $_option): ?>
            <dt><?php echo $this->escapeHtml($_option['label']); ?></dt>
            <dd>
            <?php if (isset($_option['custom_view']) && $_option['custom_view']): ?>
                <?php echo $this->getCustomizedOptionValue($_option); ?>
            <?php else: ?>
                <?php $_option = $this->getFormattedOption($_option['value']); ?>
                <?php echo $_option['value']; ?>
                <?php if (isset($_option['remainder']) && $_option['remainder']): ?>
                    <span id="<?php echo $_dots = 'dots' . uniqid(); ?>"> ...</span>
                    <span id="<?php echo $_id = 'id' . uniqid(); ?>"><?php echo $_option['remainder']; ?></span>

                    <script type="text/javascript">
                        $('<?php echo $_id; ?>').hide();
                        $('<?php echo $_id; ?>').up().observe('mouseover', function(){$('<?php echo $_id; ?>').show();});
                        $('<?php echo $_id; ?>').up().observe('mouseover', function(){$('<?php echo $_dots;?>').hide();});
                        $('<?php echo $_id; ?>').up().observe('mouseout',  function(){$('<?php echo $_id; ?>').hide();});
                        $('<?php echo $_id; ?>').up().observe('mouseout',  function(){$('<?php echo $_dots; ?>').show();});
                    </script>
                <?php endif; ?>
            <?php endif; ?>
            </dd>
        <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <?php echo $this->escapeHtml($_item->getDescription()); ?>
<?php endif; ?>
