<?php
/**
 * @category     Peppermint
 * @package      Peppermint_Customer
 * @author       Ketevani Revazishvili <techteam@rockar.com>
 * @copyright    Copyright (c) 2020 Rockar, Ltd (http://rockar.com)
 */

$lastLoginDateAdmin = $this->getLastLoginDate();
$lastLoginDateStore = $this->getStoreLastLoginDate();

$createDateAdmin    = $this->getCreateDate();
$createDateStore    = $this->getStoreCreateDate();

$creditCustomerId   = $this->getCustomer()->getCreditCheckCustomerId();
$primaryNumber       = $this->getCustomer()->getPrimaryNumber();
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-customer-view"><?php echo $this->__('Personal Information') ?></h4>
    </div>
    <fieldset>
        <table cellspacing="2" class="box-left">
            <tr>
                <td><strong><?php echo $this->__('Last Logged In:') ?></strong></td>
                <td><?php echo $lastLoginDateAdmin ?> (<?php echo $this->getCurrentStatus() ?>)</td>
            </tr>
            <?php if ($lastLoginDateAdmin != $lastLoginDateStore): ?>
                <tr>
                    <td><strong><?php echo $this->__('Last Logged In (%s):', $this->getStoreLastLoginDateTimezone()) ?></strong></td>
                    <td><?php echo $lastLoginDateStore ?> (<?php echo $this->getCurrentStatus() ?>)</td>
                </tr>
            <?php endif; ?>
            <tr>
                <td><strong><?php echo $this->__('Confirmed email:') ?></strong></td>
                <td><?php echo $this->getIsConfirmedStatus() ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Account Created on:') ?></strong></td>
                <td><?php echo $createDateAdmin ?></td>
            </tr>
            <?php if ($createDateAdmin != $createDateStore): ?>
                <tr>
                    <td><strong><?php echo $this->__('Account Created on (%s):', $this->getStoreCreateDateTimezone()) ?></strong></td>
                    <td><?php echo $createDateStore ?></td>
                </tr>
            <?php endif; ?>
            <tr>
                <td><strong><?php echo $this->__('Account Created in:') ?></strong></td>
                <td><?php echo $this->escapeHtml($this->getCreatedInStore()); ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Customer Group:') ?></strong></td>
                <td><?php echo $this->escapeHtml($this->getGroupName()) ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Primary phone number:') ?></strong></td>
                <td><?php echo $this->escapeHtml($primaryNumber) ?></td>
            </tr>
            <?php if ($creditCustomerId): ?>
                <tr>
                    <td><strong><?php echo $this->__('Credit Customer ID:') ?></strong></td>
                    <td><?php echo $this->escapeHtml($creditCustomerId) ?></td>
                </tr>
            <?php endif; ?>
        </table>
        <address class="box-right">
            <strong><?php echo $this->__('Default Billing Address') ?></strong><br/>
            <?php echo $this->maliciousCodeFilter($this->getBillingAddressHtml()) ?>
        </address>
    </fieldset>
</div>
<?php echo $this->getChildHtml('', true, true); ?>
