<?php
/**
 * @category  Peppermint
 * @package   Peppermint_Customer
 * @author    Craig Goodspeed <techteam@rockar.com>
 * @copyright Copyright (c) 2020 Rockar Ltd (http://rockar.com)
 */
?>
<?php
/**
 * @var $this Rockar_Customer_Block_Documents
 */
?>
<div class="customer-documents row">
    <!-- Include table with uploaded documents -->
    <?php echo $this->getChildHtml('customer_documents_list'); ?>
</div>
