<?php
/**
 * @category design
 * @package rockar_default
 * @author Girts Livzenieks <techteam@rockar.com>
* @copyright Copyright (c) 2018 Rockar Ltd (http://rockar.com)
 *
 * @var $this Mage_Page_Block_Html_CookieNotice
 */
?>
<?php if ((Mage::helper('core/cookie')->isUserNotAllowSaveCookie()) && (!Mage::helper('rockar_all')->checkIsInStore())): ?>
    <div class="global-site-notice notice-cookie" id="notice-cookie-block">
        <div class="notice-inner">
            <div class="notice-text">
                <?php echo $this->getCookieRestrictionBlockContent(); ?>
                <div class="actions">
                    <a class="button" onclick="allowSaveCookie();">
                        <span><?php echo $this->__('Confirm'); ?></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
<script type="text/javascript">
    /* <![CDATA[ */
    function allowSaveCookie() {
        Mage.Cookies.set('<?php echo Mage_Core_Helper_Cookie::IS_USER_ALLOWED_SAVE_COOKIE; ?>', '<?php echo Mage::helper('core/cookie')->getAcceptedSaveCookiesWebsiteIds()?>', new Date(new Date().getTime() + <?php echo Mage::helper('core/cookie')->getCookieRestrictionLifetime() ?> * 1000));
        if (Mage.Cookies.get('<?php echo Mage_Core_Helper_Cookie::IS_USER_ALLOWED_SAVE_COOKIE; ?>')) {
            jQuery('#notice-cookie-block').slideUp();
        }
    }
    jQuery('#notice-cookie-block').show();
    /* ]]> */
</script>
<?php endif; ?>


