<h3>Jaguar</h3>
<p>Can be added via <code><strong>$jaguar</strong></code> SCSS variable</p>

<h4 class="styleGuide-h4 jaguar">Jaguar Regular <code>font-weight: <strong>$fw-normal</strong>;</code></h4>
<p style="font-family: 'Jaguar', Arial, sans-serif; font-size: 18px; font-weight: 400; font-style: normal;">
    Regular text is here.
</p>
<p style="font-family: 'Jaguar', Arial, sans-serif; font-size: 18px; font-weight: 400; font-style: italic;">
    Italic text is here.
</p>

<h4 class="styleGuide-h4 jaguar">Jaguar Bold <code>font-weight: <strong>$fw-bold</strong>;</code></h4>
<p style="font-family: 'Jaguar', Arial, sans-serif; font-size: 18px; font-weight: 700; font-style: normal;">
    Regular text is here.
</p>
<p style="font-family: 'Jaguar', Arial, sans-serif; font-size: 18px; font-weight: 700; font-style: italic;">
    Italic text is here.
</p>

<h4 class="styleGuide-h4 jaguar">Jaguar ExtraBold (Black) <code>font-weight: <strong>$fw-black</strong>;</code></h4>
<p style="font-family: 'Jaguar', Arial, sans-serif; font-size: 18px; font-weight: 900; font-style: normal;">
    Regular text is here.
</p>
<p style="font-family: 'Jaguar', Arial, sans-serif; font-size: 18px; font-weight: 900; font-style: italic;">
    Italic text is here.
</p>
<hr>
<h3>Proxima Nova</h3>
<p>Can be added via <code><strong>$proximanova</strong></code> SCSS variable</p>

<h4 class="styleGuide-h4 proxima">Proxima Nova Light <code>font-weight: <strong>$fw-light</strong>;</code></h4>
<p style="font-family: 'Proxima Nova', Arial, sans-serif; font-size: 18px; font-weight: 200; font-style: normal;">
    Regular text is here.
</p>
<p style="font-family: 'Proxima Nova', Arial, sans-serif; font-size: 18px; font-weight: 200; font-style: italic;">
    Italic text is here.
</p>

<h4 class="styleGuide-h4 proxima">Proxima Nova Regular <code>font-weight: <strong>$fw-regular</strong>;</code></h4>
<p style="font-family: 'Proxima Nova', Arial, sans-serif; font-size: 18px; font-weight: 400; font-style: normal;">
    Regular text is here.
</p>
<p style="font-family: 'Proxima Nova', Arial, sans-serif; font-size: 18px; font-weight: 400; font-style: italic;">
    Italic text is here.
</p>

<h4 class="styleGuide-h4 proxima">Proxima Nova Semibold <code>font-weight: <strong>$fw-semibold</strong>;</code></h4>
<p style="font-family: 'Proxima Nova', Arial, sans-serif; font-size: 18px; font-weight: 600; font-style: normal;">
    Regular text is here.
</p>
<p style="font-family: 'Proxima Nova', Arial, sans-serif; font-size: 18px; font-weight: 600; font-style: italic;">
    Italic text is here.
</p>

<h4 class="styleGuide-h4 proxima">Proxima Nova Bold <code>font-weight: <strong>$fw-bold</strong>;</code></h4>
<p style="font-family: 'Proxima Nova', Arial, sans-serif; font-size: 18px; font-weight: 700; font-style: normal;">
    Regular text is here.
</p>
<p style="font-family: 'Proxima Nova', Arial, sans-serif; font-size: 18px; font-weight: 700; font-style: italic;">
    Italic text is here.
</p>
<hr>
<h3>Helvetica Neue</h3>
<p>Can be added via <code><strong>$helvetica</strong></code> SCSS variable</p>

<h4 class="styleGuide-h4 helvetica">Helvetica Neue Thin (Light) <code>font-weight: <strong>$fw-light</strong>;</code></h4>
<p style="font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 18px; font-weight: 200; font-style: normal;">
    Regular text is here.
</p>
<p style="font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 18px; font-weight: 200; font-style: italic;">
    Italic text is here.
</p>

<h4 class="styleGuide-h4 helvetica">Helvetica Neue Regular <code>font-weight: <strong>$fw-normal</strong>;</code></h4>
<p style="font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 18px; font-weight: 400; font-style: normal;">
    Regular text is here.
</p>
<p style="font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 18px; font-weight: 400; font-style: italic;">
    Italic text is here.
</p>

<h4 class="styleGuide-h4 helvetica">Helvetica Neue Bold <code>font-weight: <strong>$fw-bold</strong>;</code></h4>
<p style="font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 18px; font-weight: 700; font-style: normal;">
    Regular text is here.
</p>
<p style="font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 18px; font-weight: 700; font-style: italic;">
    Italic text is here.
</p>
<hr>
<h3>Myriad Pro</h3>
<p>Can be added via <code><strong>$myriad</strong></code> SCSS variable</p>

<h4 class="styleGuide-h4 myriad">Myriad Pro Regular <code>font-weight: <strong>$fw-normal</strong>;</code></h4>
<p style="font-family: 'Myriad Pro', Arial, sans-serif; font-size: 18px; font-weight: 400; font-style: normal;">
    Regular text is here.
</p>
<p style="font-family: 'Myriad Pro', Arial, sans-serif; font-size: 18px; font-weight: 400; font-style: italic;">
    Italic text is here.
</p>

<h4 class="styleGuide-h4 myriad">Myriad Pro Bold <code>font-weight: <strong>$fw-bold</strong>;</code></h4>
<p style="font-family: 'Myriad Pro', Arial, sans-serif; font-size: 18px; font-weight: 700; font-style: normal;">
    Regular text is here.
</p>
<p style="font-family: 'Myriad Pro', Arial, sans-serif; font-size: 18px; font-weight: 700; font-style: italic;">
    Italic text is here.
</p>
