<?php
/**
 * @category design
 * @package rockar_default
 * @author Dmitrijs Sitovs <dmitrijssh@scandiweb.com / dsitovs@gmail.com>
 * @copyright Copyright (c) 2016 Scandiweb, Ltd (http://scandiweb.com)
 * @license http://opensource.org/licenses/afl-3.0.php Academic Free License (AFL 3.0)
 *
 * @var $this Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<html class="loading styleguide-page">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body @mousedown="closeDropDowns">
    <?php
        echo $this->getChildHtml('after_body_start');
        echo $this->getChildHtml('content');
        echo $this->getChildHtml('before_body_end');
        echo $this->getAbsoluteFooter();
        echo $this->getChildHtml('before_body_end_scripts')
    ?>
</body>
</html>
