<?php
/**
 * @category  Design
 * @package   Peppermint
 * @author    Jez Horton <jez.horton@rockar.com>
* @copyright Copyright (c) 2020 Rockar Ltd (http://rockar.com)
 *
 * @var $this Rockar_MySavedCars_Block_SavedCars
 */
?>
<?php if ($this->getWishlistItems()->count()): ?>
    <div class="my-saved-cars-section row" id="my-saved-cars">
        <div class="col-12">
            <app-accordion title='<?php echo $this->__('My Wishlist'); ?>' class-name="accordion-light" type="right-down">
                <li>
                    <div class="accordion-content">
                        <div class="my-account-wrapper my-part-exchange">
                            <div class="my-account-header">
                                <p class="my-account-heading h-common"><?php echo $this->__('My Wishlist'); ?></p>
                                <p class="my-account-subheading"><?php echo $this->__('Vehicles added to my wishlist'); ?></p>
                            </div>
                            <div class="my-account-content my-saved-cars-wrapper">
                                <?php foreach ($this->getWishlistItems() as $wishlistItem): ?>
                                    <?php $product = $this->getSavedProduct($wishlistItem); ?>
                                        <app-my-saved-cars
                                            :car-extras='<?php echo $this->getExtrasJson($wishlistItem); ?>'
                                            :is-full-configurator='<?php echo $this->getIsFullConfigurator($wishlistItem); ?>'
                                            user-title="<?php echo htmlentities($wishlistItem->getDescription()); ?>"
                                            car-title="<?php echo Mage::helper('rockar_catalog/vehicle')->getTitle($wishlistItem->getProduct()); ?>"
                                            car-description="<?php echo Mage::helper('rockar_catalog/vehicle')->getSubtitle($wishlistItem->getProduct()); ?>"
                                            :car-images='<?php echo $this->getProductMedia($product); ?>'
                                            car-cover-exterior='<?php echo $this->getExteriorImage($product); ?>'
                                            car-cover-interior='<?php echo $this->getInteriorImage($product); ?>'
                                            :car-extras='<?php echo $this->getExtrasJson($wishlistItem); ?>'
                                            :view-urls='<?php echo $this->getViewUrls($wishlistItem); ?>'
                                            :car-stock='<?php echo ($wishlistItem->getProduct()->isAvailable()) ? 1 : 0; ?>'
                                            car-redirect-url='<?php echo $this->getChooseUrl($wishlistItem); ?>'
                                            car-finder-url='<?php echo $this->getCarFinderUrl(); ?>'
                                            car-remove-url='<?php echo Mage::helper('rockar_mysavedcars')->getRemoveUrl($wishlistItem); ?>'
                                            car-added-date='<?php echo $wishlistItem->getAddedAt(); ?>'
                                            :is-full-configurator='<?php echo $this->getIsFullConfigurator($wishlistItem); ?>'
                                            :finance-data='<?php echo $this->getFinanceQuoteData($wishlistItem); ?>'
                                            :price-available='<?php echo $this->checkPriceAvailable($wishlistItem) ? 'true' : 'false'; ?>'
                                            :wishlist-item-price='<?php echo $this->getSavedWishlistItemPrice($wishlistItem); ?>'
                                        ></app-my-saved-cars>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                </li>
            </app-accordion>
        </div>
    </div>
<?php endif; ?>
