<?php
/**
 * @category design
 * @package rockar_default
 * @author Dmitrijs Sitovs <techteam@rockar.com>
* @copyright Copyright (c) 2016 Rockar Ltd (http://rockar.com)
 *
 * @var $this Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<html>
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body class="page-empty <?php echo $this->getBodyClass()?$this->getBodyClass():'' ?>">
    <?php echo $this->getChildHtml('after_body_start') ?>
    <?php echo $this->getChildHtml('global_messages') ?>
    <?php echo $this->getChildHtml('content') ?>
    <?php echo $this->getChildHtml('before_body_end') ?>
    <?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
