<?php
/**
 * @category design
 * @package rockar\default2
 * @author Edgars Joja <techteam@rockar.com>
* @copyright Copyright (c) 2018 Rockar Ltd (http://rockar.com)
 *
 * @var $this Mage_Page_Block_Html_Header
 */
?>
<?php
/** @var Rockar_Cms_Helper_Data $cmsHelper */
$cmsHelper = Mage::helper('rockar_cms');

$switcherData = $cmsHelper->getWebsiteSwitcherData();
$allHelper = Mage::helper('rockar_all');
$isInStore = $allHelper->checkIsInStore();
$storeCode = $allHelper->getInStoreCode();
$dealerId = $allHelper->getDealerId();
$store = $storeCode ? Mage::helper('peppermint_localstores/data')->getStoreFromCode($storeCode) : '';
$storeName = $store ? preg_replace('/.\(.+\)/', '', $store->getName()) : '';
?>

<div class="page-loader"><div class="show-loading"></div></div>

<div class="nav-wrap">
    <header class="navigation-bar" role="banner">
        <div class="navigation-bar-wrapper inner-container">
            <nav class="navigation-menu <?php echo $isInStore ? 'instore' : ''; ?>">
                <div class="navigations-list">
                    <div class="custom-nav-wrapper">
                        <ul class="custom-nav">
                            <?php if ($isInStore): ?>
                                <div class="in-store-indicator">
                                    <?php echo "In-Store | $storeName | $storeCode |&nbsp;<span class=\"dealer-id\">$dealerId</span>"; ?>
                                </div>
                            <?php endif; ?>
                            <li class="account-toggle">
                                <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                                    <?php $notificationCount = (int)Mage::helper('rockar_sales/messages')->getNotificationCount(); ?>
                                    <a href="#">
                                        <span class="badge" <?php echo !$notificationCount ? 'style="display:none;"' : ''; ?>><?php echo $notificationCount; ?></span>
                                        <span class="icon icon-account">&nbsp;</span>
                                    </a>
                                <?php else: ?>
                                    <a href="<?php echo Mage::helper('customer')->getDashboardUrl(); ?>"><span class="icon icon-account no-after">&nbsp;</span></a>
                                <?php endif; ?>

                                <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                                    <ul>
                                        <li>
                                            <a href="<?php echo Mage::helper('customer')->getDashboardUrl(); ?>">
                                                <?php echo $this->__('My Account'); ?>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="<?php echo Mage::helper('customer')->getLogoutUrl(); ?>">
                                                <?php echo $this->__('Logout'); ?>
                                            </a>
                                        </li>
                                    </ul>
                                <?php endif; ?>
                            </li>
                            <li>
                                <a href="<?php echo Mage::helper('checkout/url')->getCheckoutUrl(); ?>">
                                    <?php if (!Mage::helper('rockar_all')->checkIsInStore()): ?>
                                        <span class="badge"><?php echo (int) Mage::helper('checkout/cart')->getSummaryCount(); ?></span>
                                    <?php endif; ?>
                                    <span class="icon icon-cart">&nbsp;</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <?php echo $this->getChildHtml('navigation'); ?>
                </div>
            </nav>
            <div class="logotype brand-logo">
                 <a href="<?php echo $this->getUrl(''); ?>" class="logo">
                     <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>"/>
                 </a>
            </div>
        </div>
        <div class="store-switcher">
            <a href="#">
                <!-- @todo: Replace with Jlr_Cms_Helper_Data::getWebsiteSwitcherData when migrating to JLR -->
                <span><?php echo $this->__('Store switcher') ?></span>
            </a>
        </div>
    </header>

    <header class="navigation-bar-mobile" role="banner">
        <div class="main-nav">
            <div class="logotypes">
                <a href="<?php echo $this->getUrl(''); ?>" class="logo">
                    <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>"/>
                </a>
            </div>

            <div class="right-nav-wrapper">
                <nav class="navigation-bar-user">
                    <ul>
                        <li>
                            <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                                <?php $notificationCount = (int)Mage::helper('rockar_sales/messages')->getNotificationCount(); ?>
                                <a href="#" class="account-toggle">
                                    <span class="badge" <?php echo !$notificationCount ? 'style="display:none;"' : ''; ?>><?php echo $notificationCount; ?></span>
                                    <span class="icon icon-account">&nbsp;</span>
                                </a>
                            <?php else: ?>
                                <a href="<?php echo Mage::helper('customer')->getDashboardUrl(); ?>"><span class="icon icon-account no-after">&nbsp;</span></a>
                            <?php endif; ?>

                            <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                                <ul>
                                    <li>
                                        <a href="<?php echo Mage::helper('customer')->getDashboardUrl(); ?>">
                                            <?php echo $this->__('My Account'); ?>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="<?php echo Mage::helper('customer')->getLogoutUrl(); ?>">
                                            <?php echo $this->__('Logout'); ?>
                                        </a>
                                    </li>
                                </ul>
                            <?php endif; ?>
                        </li>
                        <li>
                            <a href="<?php echo Mage::helper('checkout/url')->getCheckoutUrl(); ?>">
                                <span class="icon icon-cart">&nbsp;</span>
                            </a>
                        </li>
                    </ul>
                </nav>

                <nav class="navigation-bar-menu">
                    <a href="#" class="navbar-toggle hamburger hamburger-cancel"><span class="icon"></span></a>
                    <?php echo $this->getChildHtml('navigation'); ?>
                </nav>
            </div>
        </div>
        <?php if ($switcherData): ?>
            <div class="store-switcher">
                <a href="<?php echo isset($switcherData['url']) ? $switcherData['url'] : '#' ?>">
                    <span><?php echo isset($switcherData['label']) ? $switcherData['label'] : $this->__('Switch store') ?></span>
                </a>
            </div>
        <?php endif ?>
    </header>
</div>
<app-notification></app-notification>
