<?php
/**
 * @category  Peppermint
 * @package   Peppermint_All
 * @author    Ausma Smite <techteam@rockar.com>
 * @copyright Copyright (c) 2021 Rockar Ltd (http://rockar.com)
 *
 */
?>

<h4>L</h4>
<a class="dsp2-link" href="#">I am a link</a>
<br>
<br>
<a class="dsp2-link disabled" href="#">Disabled</a>
<br>
<br>
<p>Back link on page level:</p>
<a class="dsp2-link previous"><span class="arrow-back"></span>Previous</a>
<br>
<br>
<p>Finance Overlay:</p>
<a class="dsp2-link"><span class="arrow-up"></span>What is MINI Select Finance?</a>
<br>
<br>
<a class="dsp2-link"><span class="icon-video"></span>Watch Video</a>
<br>
<br>
<p>Trade-in Overlay:</p>
<a class="dsp2-link"><span class="arrow-down"></span>More info</a>
<br>
<br>

<h4>S</h4>
<a class="dsp2-link-s" href="#">I am a link</a>
<br>
<br>
<a class="dsp2-link-s disabled" href="#">Disabled</a>
<br>
<br>
<a class="dsp2-link-s previous"><span class="arrow-back"></span>Previous</a>
<br>
<br>
<a class="dsp2-link-s"><span class="arrow-down"></span>More info</a>
<br>
<br>

<h4>Links with icon</h4>
<p>Finance Filter box:</p>
<a class="dsp2-link filter"><span class="arrow-next"></span>More Filters</a>
<br>


