<?php
/**
 * @category  Peppermint
 * @package   Peppermint_All
 * @author    Ausma Smite <techteam@rockar.com>
 * @copyright Copyright (c) 2021 Rockar Ltd (http://rockar.com)
 *
 */
?>

<h3>MINI Fonts</h3>
<hr>
<section class="styleguide-fonts">
    <div>
        <p class="font-regular">MINI Sans-serif Regular |  font-family: $mini-sans-serif-regular</p>
        <p class="font-regular">The Quick Blue MINI</p>
    </div>
    <hr>
    <div>
        <p class="font-bold">MINI Sans-serif Bold | font-family: $mini-sans-serif-bold</p>
        <p class="font-bold">The Quick Blue MINI</p>
    </div>
    <hr>
    <div>
        <p class="font-serif-regular">MINI Serif Regular | font-family: $mini-serif-regular</p>
        <p class="font-serif-regular">The Quick Blue MINI</p>
    </div>
    <hr>
    <div>
        <p class="font-serif-bold">MINI Serif Bold | font-family: $mini-serif-bold</p>
        <p class="font-serif-bold">The Quick Blue MINI</p>
    </div>
</section>
