<div>
    <div class="warning-msg">
        This is the warning message
    </div>
</div>

<div>
    <div class="error-msg">
        This is the error message
    </div>
</div>

<div>
    <div class="success-msg">
        This is the success message
    </div>
</div>

<h3>Global warning</h3>

<app-global-warning
        type="error"
        message="Unfortunately we were unable to verify your address, please check your details and try again."
        :show=true>
</app-global-warning>
