<h4 style="margin-bottom: 10px;">Next/Back/More</h4>
<h6>.arrow-back</h6>
<a href class="arrow-back"></a>
<h6>.arrow-next</h6>
<a href class="arrow-next"></a>

<hr>

<h4>Buttons</h4>

<br>

<div class="grid">
    <div class="row">
        <div class="col-6">
            <h5>The Money button</h5>
            <br>
            <h6>button dsp2-money</h6>
            <button type="button" name="button" class="button dsp2-money">Master</button>
            <br>
            <br>
            <h6>button dsp2-money disabled</h6>
            <button type="button" name="button" class="button dsp2-money disabled">Disabled</button>
        </div>
        <div class="col-6">
            <h5>The Next Best Action</h5>
            <br>
            <h6>button dsp2-action</h6>
            <button type="button" name="button" class="button dsp2-action">Master</button>
            <br>
            <br>
            <h6>button dsp2-action disabled</h6>
            <button type="button" name="button" class="button dsp2-action disabled">Disabled</button>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <h5>Outline</h5>
            <br>
            <h6>button dsp2-outline</h6>
            <button type="button" name="button" class="button dsp2-outline">Master</button>
            <br>
            <br>
            <h6>button dsp2-outline disabled</h6>
            <button type="button" name="button" class="button dsp2-outline disabled">Disabled</button>
        </div>
    </div>
</div>
