<h1>The Quick Blue BMW | tag/class H1 | 64px</h1>
<br>
<h2>The Quick Blue BMW | tag/class H2 | 48px</h2>
<br>
<h3>The Quick Blue BMW | tag/class H3 | 32px</h3>
<br>
<h4>The Quick Blue BMW | tag/class H4 | 24px</h4>
<br>
<h5>The Quick Blue BMW | tag/class H5 | 20px</h5>
<br>
<h6>The Quick Blue BMW | tag/class H6 | 16px </h6>

<hr>

<p class="h7">The Quick Blue BMW | class .h7 | 20px</p>
<br>
<p class="h8">The Quick Blue BMW | class .h8 | 16px</p>

<hr>

<p class="dsp2-subtitle">The Quick Blue BMW | class .dsp2-subtitle | 16px</p>
<br>
<p class="dsp2-subtitle-s">The Quick Blue BMW | class .dsp2-subtitle-s | 14px</p>
<br>
<p class="dsp2-body">The Quick Blue BMW | class .dsp2-body | 16px</p>
<br>
<p class="dsp2-body-s">The Quick Blue BMW | class .dsp2-body-s | 14px</p>
<br>
<p class="dsp2-link">The Quick Blue BMW | class .dsp2-link | 16px</p>
<br>
<p class="dsp2-link-s">The Quick Blue BMW | class .dsp2-link-s | 14px</p>
<br>
<p class="dsp2-caption">The Quick Blue BMW | class .dsp2-caption | 12px</p>
<br>
<p class="dsp2-label">The Quick Blue BMW | class .dsp2-label | 12px</p>
<br>
<p class="dsp2-label-s">The Quick Blue BMW | class .dsp2-label-s | 10px</p>
<br>
