<h4>L</h4>
<a class="dsp2-link" href="#">I am a link</a>

<br>
<br>

<a class="dsp2-link disabled" href="#">Disabled</a>

<br>
<br>

<a class="dsp2-link"><span class="arrow-back"></span>Previous</a>

<br>
<br>

<a class="dsp2-link disabled"><span class="arrow-back"></span>Disabled</a>

<br>
<br>

<h4>S</h4>
<a class="dsp2-link-s" href="#">I am a link</a>

<br>
<br>

<a class="dsp2-link-s disabled" href="#">Disabled</a>

<br>
<br>

<a class="dsp2-link-s"><span class="arrow-back"></span>Previous</a>

<br>
<br>

<a class="dsp2-link-s disabled"><span class="arrow-back"></span>Disabled</a>

<br>
<br>

<h4>Links with icon</h4>
<a class="dsp2-link"><span class="icon-cross"></span>More Filters</a>
<br>
<a class="dsp2-link"><span class="arrow-down"></span>More info</a>


