<button class="button dsp2-money" @click="openInModal('modalConfirmExample')" style="margin-bottom: 5px">Open Confirmation Popup</button>

<app-modal v-ref:modal-confirm-example>
    <div slot="content">
        <h3>This is example heading text</h3>
        <div>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas lacinia nec risus ut pulvinar. Aliquam pretium libero ac sagittis dapibus. Nunc bibendum pulvinar mauris, nec ornare massa porta non. Maecenas vestibulum id ex laoreet posuere. Etiam nec lacus bibendum, ornare ligula ut, luctus metus.</p>
        </div>
        <div class="grid">
            <div class="actions row">
                <div class="col-6">
                    <button type="button" name="button" class="dsp2-outline">
                        <span>Cancel</span>
                    </button>
                </div>
                <div class="col-6">
                    <button type="button" name="button" class="dsp2-money">
                        <span>Confirm</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</app-modal>
