<h3>BMWTypeNext</h3>
<p>
    BMW uses the corporate font face BMWTypeNext for all text elements in different but predefined sizes and weights.
</p>

<hr>

<section class="styleguide-fonts">
    <div>
        <p class="font-regular">Regular |  font-family: $bmw</p>
        <p class="font-regular">The Quick Blue BMW</p>
        <p class="font-regular">Only used for very special cases.</p>
    </div>

    <hr>

    <div>
        <p class="font-light">Light | font-family: $bmw-light</p>
        <p class="font-light">The Quick Blue BMW</p>
        <p class="font-light">Used for big headlines, sublines and body text.</p>
    </div>

    <hr>

    <div>
        <p class="font-bold">Bold | font-family: $bmw-bold</p>
        <p class="font-bold">The Quick Blue BMW</p>
        <p class="font-bold">
            Used for clickable text and to highlight important imformation within static texts and databases like tables. Do not overuse bold fonts. Not only used for interactive texts anymore.
        </p>
    </div>

    <hr>
</section>

<h3>Switching from Desktop to Mobile</h3>
<p>
    S (Mobile) is the only breakpoint that uses a slightly different batch of our font styles. There are no new font sizes or style definitions, we just exclude H1, H2 and label 2 as they would appear as too big on a mobile screen. In return those excluded styles get translated to another existing style.
</p>
<p>
    H1 and H2 on X,L,M breakpoints translate to H3 on S and label 1 on X,L,M translates to label 2 on S. Try resizing the screen to see it in action.
</p>
