<?php
/**
 * @category  design
 * @package   rockar_mini
 * @author    Krists Dadzitis <techteam@rockar.com>
 * @copyright Copyright (c) 2020 Rockar Ltd (http://rockar.com)
 *
 * @var $this Mage_Page_Block_Html_Header
 */
?>
<?php
/** @var Rockar_Cms_Helper_Data $cmsHelper */
$cmsHelper = Mage::helper('rockar_cms');

$inStoreCookieValue = Mage::getModel('core/cookie')->get('in_store') ?: 1;
$inStoreGetVar = strpos($this->getUrl(''), '?') ? '&' : '?';
$inStoreGetVar .= 'in_store=' . $inStoreCookieValue;

$url = $this->getUrl('');
$url .= Mage::helper('rockar_all')->checkIsInStore() ? $inStoreGetVar : '';
$gdprInitialPreferencesPopup = $this->getChildHtml('gdpr_initial_preferences_popup');
$gdprBankPreferencesPopup = $this->getChildHtml('gdpr_bank_preferences');
$gdprHelper = Mage::helper('rockar_gdpr');

$switcherData = $cmsHelper->getWebsiteSwitcherData();
$allHelper = Mage::helper('rockar_all');
$isInStore = $allHelper->checkIsInStore();
$storeCode = $allHelper->getInStoreCode();
$dealerId = $allHelper->getDealerId();
$store = $storeCode ? Mage::helper('peppermint_localstores/data')->getStoreFromCode($storeCode) : '';
$storeName = $store ? preg_replace('/.\(.+\)/', '', $store->getName()) : '';
?>

<div class="page-loader"><div class="show-loading"></div></div>

<?php if (Mage::getSingleton('customer/session')->isLoggedIn() && $gdprHelper->getGdprInitialPreferencesEnabled()): ?>
    <app-gdpr-initial-preferences
        gdpr-save-url="<?php echo Mage::helper('rockar_gdpr')->getCustomerOptionSaveUrl(); ?>"
        :gdpr-channels='<?php echo Mage::helper('rockar_gdpr')->getActiveChannels(true); ?>'
        :gdpr-options='<?php echo Mage::helper('rockar_gdpr')->getActiveOptions(true); ?>'
        :gdpr-customer-options='<?php echo Mage::helper('rockar_gdpr')->getCurrentCustomerOptions(true); ?>'
        :gdpr-cms-blocks-enabled='<?php echo Mage::helper('rockar_gdpr')->getGdprCmsEnabled(); ?>'
        my-account-url='<?php echo $this->getUrl('customer/account'); ?>'
        v-ref:gpdr-initial-preferences
    >
        <div slot="gdpr_initial_preferences_popup" class="vue-slot"><?php echo $gdprInitialPreferencesPopup; ?></div>
        <div slot="gdpr_bank_preferences" class="vue-slot"><?php echo $gdprBankPreferencesPopup; ?></div>
    </app-gdpr-initial-preferences>
<?php endif; ?>

<div class="nav-wrap">
    <header class="navigation-bar" role="banner">
        <div class="navigation-bar-wrapper">
            <div class="logotype brand-logo">
                <a href="<?php echo $url; ?>" class="logo">
                    <img src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>"/>
                </a>
            </div>

            <nav class="navigation-menu <?php echo Mage::helper('rockar_all')->checkIsInStore() ? 'instore' : ''; ?>">
                <div class="navigations-list">
                    <div class="custom-nav-wrapper">
                        <ul class="custom-nav">
                            <?php if ($isInStore): ?>
                                <div class="in-store-indicator">
                                    <?php echo "In-Store | $storeName | $storeCode |&nbsp;<span class=\"dealer-id\">$dealerId</span>"; ?>
                                </div>
                            <?php endif; ?>
                            <li class="account-toggle">
                                <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                                    <?php $notificationCount = (int)Mage::helper('rockar_sales/messages')->getNotificationCount(); ?>
                                    <a href="#">
                                        <span class="badge" <?php echo !$notificationCount ? 'style="display:none;"' : ''; ?>><?php echo $notificationCount; ?></span>
                                        <span class="icon icon-account">&nbsp;</span>
                                    </a>
                                <?php else: ?>
                                    <a href="<?php echo Mage::helper('customer')->getDashboardUrl(); ?>"><span class="icon icon-account no-after">&nbsp;</span></a>
                                <?php endif; ?>

                                <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                                    <ul>
                                        <li>
                                            <a href="<?php echo Mage::helper('customer')->getDashboardUrl(); ?>">
                                                <?php echo $this->__('My Account'); ?>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="<?php echo Mage::helper('customer')->getLogoutUrl(); ?>">
                                                <?php echo $this->__('Logout'); ?>
                                            </a>
                                        </li>
                                    </ul>
                                <?php endif; ?>
                            </li>
                            <li>
                                <a href="<?php echo Mage::helper('checkout/url')->getCheckoutUrl(); ?>">
                                    <?php if (!Mage::helper('rockar_all')->checkIsInStore()): ?>
                                        <span class="badge"><?php echo (int) Mage::helper('checkout/cart')->getSummaryCount(); ?></span>
                                    <?php endif; ?>
                                    <span class="icon icon-cart">&nbsp;</span>
                                </a>
                            </li>

                            <li class="logotype">
                                <a href="<?php echo $url ?>" class="logo rockar">
                                    <img src="<?php echo $this->getSkinUrl('images/rockar-logo.png'); ?>" alt="<?php echo $this->__('Rockar Logo'); ?>">
                                </a>
                            </li>
                        </ul>
                    </div>
                    <?php echo $this->getChildHtml('navigation'); ?>
                </div>
            </nav>
        </div>
        <div class="store-switcher">
            <a href="#">
                <!-- @todo: Replace with Jlr_Cms_Helper_Data::getWebsiteSwitcherData when migrating to JLR -->
                <span><?php echo $this->__('Store switcher'); ?></span>
            </a>
        </div>
    </header>

    <header class="navigation-bar-mobile" role="banner">
        <div class="main-nav">
            <div class="logotypes">
                <a href="<?php echo $this->getUrl(''); ?>" class="logo">
                    <img src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>"/>
                </a>
                <a href="<?php echo $this->getUrl(''); ?>" class="logo rockar">
                    <img src="<?php echo $this->getSkinUrl('images/rockar-logo.png'); ?>" alt="<?php echo $this->__('Rockar Logo'); ?>">
                </a>
            </div>

            <div class="right-nav-wrapper">
                <nav class="navigation-bar-user">
                    <ul>
                        <li>
                            <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                                <?php $notificationCount = (int)Mage::helper('rockar_sales/messages')->getNotificationCount(); ?>
                                <a href="#" class="account-toggle">
                                    <span class="badge" <?php echo !$notificationCount ? 'style="display:none;"' : ''; ?>><?php echo $notificationCount; ?></span>
                                    <span class="icon icon-account">&nbsp;</span>
                                </a>
                            <?php else: ?>
                                <a href="<?php echo Mage::helper('customer')->getDashboardUrl(); ?>"><span class="icon icon-account no-after">&nbsp;</span></a>
                            <?php endif; ?>

                            <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                                <ul>
                                    <li>
                                        <a href="<?php echo Mage::helper('customer')->getDashboardUrl(); ?>">
                                            <?php echo $this->__('My Account'); ?>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="<?php echo Mage::helper('customer')->getLogoutUrl(); ?>">
                                            <?php echo $this->__('Logout'); ?>
                                        </a>
                                    </li>
                                </ul>
                            <?php endif; ?>
                        </li>
                        <li>
                            <a href="<?php echo Mage::helper('checkout/url')->getCheckoutUrl(); ?>">
                                <span class="icon icon-cart">&nbsp;</span>
                            </a>
                        </li>
                    </ul>
                </nav>

                <nav class="navigation-bar-menu">
                    <a href="#" class="navbar-toggle hamburger hamburger-cancel"><span class="icon"></span></a>
                    <?php echo $this->getChildHtml('navigation'); ?>
                </nav>
            </div>
        </div>
        <?php if ($switcherData): ?>
            <div class="store-switcher">
                <a href="<?php echo isset($switcherData['url']) ? $switcherData['url'] : '#'; ?>">
                    <span><?php echo isset($switcherData['label']) ? $switcherData['label'] : $this->__('Switch store'); ?></span>
                </a>
            </div>
        <?php endif; ?>
    </header>
</div>
<app-notification></app-notification>
