<?php
/**
 * @category  BMW
 * @package   BMW\Checkout
 * @author    Brandon Ho <brandon.ho@partner.bmw.co.za>
 */
?>
<?php
/**
 * @var $this Rockar_FinancingOptions_Block_Checkout_Steps_Finance
 */
$data = $this->getFinanceQuoteData();
$savedData = $this->getFinanceQuoteSavedData();
?>
<app-checkout-accordion title="Choose Your Payment Option" type="right-down" class-name="accordion-light" step-code="<?php echo Rockar_FinancingOptions_Helper_Finance_Quote_Checkout::FINANCE_STEP_CODE; ?>">
    <li>
        <div class="accordion-content">
            <app-checkout-finance-overlay
                :product-id="<?php echo $data['product_id'] ?>"
                finance-url="<?php echo $data['finance_url'] ?>"
                :finance-params-origin='<?php echo $data['finance_params'] ?>'
                :finance-slider-steps='<?php echo $data['finance_slider_steps'] ?>'
                :pay-in-full-payment='<?php echo $data['pay_in_full_payment'] ?>'
                :hire-payments='<?php echo Mage::helper('rockar_all')->jsonEncode($data['hire_payments']) ?>'
                :active-payment='<?php echo $data['active_payment'] ?>'
                payment-save-url='<?php echo $data['payment_save_url'] ?>'
                :update-finance-quote="true"
                calc-type="<?php echo Rockar_FinancingOptions_Model_Calculation_Type_Abstract::CALC_TYPE_QUOTE ?>"
                confirmation-overlay-content='<?php echo Mage::helper('rockar_all')->jsonEncode($this->getChildHtml('checkout_finance_confirmation')) ?>'
                disagree-overlay-content='<?php echo Mage::helper('rockar_all')->jsonEncode($this->getChildHtml('checkout_finance_step_disagree')) ?>'
                confirmation-url="<?php echo $this->getUrl('checkout/onepage_financing/checkoutFinanceStep') ?>"
                :finance-saved-data='<?php echo $savedData ?>'
                :skip-ready='<?php echo $savedData != '' ? 'true' : 'false'; ?>'
                :instalment-group-id='<?php echo $this->getInstalmentGroupId(); ?>'
                image="<?php echo $data['image']; ?>"
                image-alt="<?php echo $data['image_alt']; ?>"
                ></app-checkout-finance-overlay>
        </div>
    </li>
</app-checkout-accordion>
