<?php
/**
 * @category  Peppermint
 * @package   Peppermint_All
 * @author    Taras Kapushchak <techteam@rockar.com>
 * @copyright Copyright (c) 2021 Rockar Ltd (http://rockar.com)
 *
 */
?>

<h3>Global warning</h3>

<app-global-warning
    type="error"
    message="Unfortunately we were unable to verify your address, please check your details and try again."
    :show=true>
</app-global-warning>

<app-global-warning
    type="success"
    message="A new OTP has been sent to ******2222"
    :show=true>
</app-global-warning>
