<?php
/**
 * @category  Peppermint
 * @package   Peppermint_All
 * @author    Taras Kapushchak <techteam@rockar.com>
 * @copyright Copyright (c) 2021 Rockar Ltd (http://rockar.com)
 *
 */
?>

<h1>The Quick Blue Motorrad | tag/class H1 | 80px (28px)</h1>
<br>
<h2>The Quick Blue Motorrad | tag/class H2 | 40px (24px)</h2>
<br>
<h3>The Quick Blue Motorrad | tag/class H3 | 32px (22px)</h3>
<br>
<h4>The Quick Blue Motorrad | tag/class H4 | 24px (16px)</h4>
<br>
<h5>The Quick Blue Motorrad | tag/class H5 | 16px (16px)</h5>
<br>
<h6>The Quick Blue Motorrad | tag/class H6 | 16px </h6>

<hr>

<p class="dsp2-subtitle">The Quick Blue Motorrad | class .dsp2-subtitle | 16px</p>
<br>
<p class="dsp2-subtitle-s">The Quick Blue Motorrad | class .dsp2-subtitle-s | 14px</p>
<br>
<p class="dsp2-body">The Quick Blue Motorrad | class .dsp2-body | 16px</p>
<br>
<p class="dsp2-body-s">The Quick Blue Motorrad | class .dsp2-body-s | 14px</p>
<br>
<p class="dsp2-link">The Quick Blue Motorrad | class .dsp2-link | 16px</p>
<br>
<p class="dsp2-link-s">The Quick Blue Motorrad | class .dsp2-link-s | 14px</p>
<br>
<p class="dsp2-caption">The Quick Blue Motorrad | class .dsp2-caption | 12px</p>
<br>
<p class="dsp2-label">The Quick Blue Motorrad | class .dsp2-label | 12px</p>
<br>
<p class="dsp2-label-s">The Quick Blue Motorrad | class .dsp2-label-s | 10px</p>
<br>
