<?php
/**
 * @category  Peppermint
 * @package   Peppermint_All
 * @author    Taras Kapushchak <techteam@rockar.com>
 * @copyright Copyright (c) 2021 Rockar Ltd (http://rockar.com)
 *
 */
?>

<h3>Motorrad Fonts</h3>
<hr>
<section class="styleguide-fonts">
    <div>
        <p class="font-regular">Motorrad Regular |  font-family: $motorrad-regular</p>
        <p class="font-regular">The Quick Blue Motorrad</p>
    </div>
    <hr>
    <div>
        <p class="font-bold">Motorrad Bold | font-family: $motorrad-bold</p>
        <p class="font-bold">The Quick Blue Motorrad</p>
    </div>
    <hr>
</section>
