<?php
/**
 * @category     Rockar2
 * @package      Rockar2_GoogleTagManager
 * @author       Dairis Rozenfelds <info@scandiweb.com>
 * @copyright    Copyright (c) 2018 Scandiweb, Inc (http://scandiweb.com)
 * @license      http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */
?>
<?php
/**
 * @var $this Rockar2_GoogleTagManager_Block_Gtm
 */
?>
<?php
$helper = Mage::helper('rockar_googletagmanager');

if ($helper->isGoogleTagManagerAvailable()) :
    $containerId = $helper->getContainerId();
    echo $this->getDataLayer(); ?>

    <!-- Google Tag Manager -->
    <script>
        (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','<?php echo $containerId; ?>');
    </script>
    <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=<?php echo $containerId; ?>"
                height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <!-- End Google Tag Manager -->
<?php endif; ?>

